### ISSUE TITLE
How to use in a project?

### ISSUE THREAD

**Issue by ankurhora** [keirantai/nodejs-fastload#3]
Hi,
i have just started to use nodejs and i am working on a project where i need to resize the image of which i have the url and save it with a definite size.
All the modelues i have used till date is like 
1) initialization 
var probe = require('probe-image-size');
2) usage
probe(url,function(err,result){
console.log(result.width);
}

but i failed to understand the iplementaion of this module.
Can you guide me through. This module is perfect for my use ( functionality)

**Comment by keirantai** [comment]
Hi @ankurhora,

This is a very simple project and inspired the http://placehold.it long time ago. The idea of this project is to download any images from a URL, cache it, modify it and then output via HTTP protocol. So what you need to do is using ExpressJS to create your web service and use `app.use()` to require this project as a middleware. Details you can find in the README.md file.
